### ISSUE TITLE
Minitest hooks don't work with rails fixtures

### ISSUE THREAD

**Issue by hschne** [jeremyevans/minitest-hooks#17] opened 2019-05-02 15:41 UTC
I'm currently using `minitest-hooks` in a Rails project where we rely heavily on fixtures. However, `before_all` does not seems to support rails test fixtures. 

For example a test similar to this one throws the error 'Minitest::UnexpectedError: NoMethodError: undefined method `[]' for nil:NilClass' at `@person = persons(:person1)`. 

```
require 'test_helper'

class TaskDataTest < ActiveSupport::TestCase
  include Minitest::Hooks

  fixtures :all

  def before_all
    @person = persons(:person1)
  end

  test 'test' do
    assert_equal(1, 1)
  end

  test 'another test' do
    assert_equal(2, 2)
  end
end
```

The error occurs in `ActiveRecord::TestFixtures' as far as I can tell, but I'm not sure what exactly goes wrong there. Similar code (e.g. replacing fixtures with factory methods or similar or placing the fixture call in the setup method) works fine. 

This is definitely something we could work around, but I'd still like to know if you have any clues/possible fixes for this issue? Ideally the sample above should 'just work' :smirk:

**Comment by jeremyevans** [comment] 2019-05-02 16:48
My guess is that `fixtures :all` does not take effect before `before_all` is called.  You'll have to find a way to load the fixtures in `before_all` before calling `persons`.  Not sure how to do that, you'll have to look at the `ActiveRecord::TextFixtures` code to find the method that loads the fixtures.  If you find out how, I'd be OK with adding instructions to the README on how to get them to work together.

As this is not a bug in minitest-hooks, I'm going to close this now.

**Closed by jeremyevans** 2019-05-02 16:48 UTC

**Comment by minghz** [comment] 2019-12-16 21:30
You could call `setup_fixtures` in the beginning of your `before(:all)` block, and `teardown_fixtures` at the end of your `after(:all)` block.
